version: '3'
services:
  app:
    image: hexa-lab:latest
    build:
      context: .
    container_name: app
    depends_on:
      - db
  db:
    image: postgres:10.4
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hexa-lab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres